climbupproject/climbupApp/urls.py
from django.urls import path
from . import views

app_name='climbupApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('load_posts/', views.load_posts, name='load_posts'),
    path('profile_page/', views.profile_page, name='profile_page'),
    path('profile_load/', views.profile_load, name='profile_load'),
    path('login_page/', views.login_page, name='login_page'),
    path('register/', views.register, name='register'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('post_new/', views.post_new, name='post_new'),
    path('get_cities/', views.get_cities, name='get_cities'),
    path('add_city/', views.add_city, name='add_city'),
    path('like_post/', views.like_post, name='like_post'),
    path('attendants/', views.attendants, name='attendants'),
    path('post_edit/', views.post_edit, name='post_edit'),
    path('delete_post/', views.delete_post, name='delete_post'),
    path('load_comments/', views.load_comments, name='load_comments'),
    path('save_comment/', views.save_comment, name='save_comment'),
]

climbupproject/climbupproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('climbupApp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

climbupproject/climbupApp/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=60)
    text = models.TextField()# allowing the user to add images to their post
    post_image = models.ImageField(upload_to='post_images/', null=True, blank=True)# ties the post to a city in the database for sorting
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='posts')# ties user to their posts
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='authored_posts')
    attendees = models.ManyToManyField(User, related_name='attending_posts', blank=True) # ties user(s) attending status to individual posts
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)# ties user(s) likes to individual posts
    created_date = models.DateTimeField(default=timezone.now)
    scheduled_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title + 'by' + self.author.username + 'on' + self.created_date.strftime('%b %d %Y')
    
    # model for comments
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')# post ties the comment to a particular post
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_authors')# foreign key to the user, tying the user to their comments
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)# comments are auto-accepted, select default to false if comments should be approved before posting to page

    class Meta:
        ordering = ['created_on']
    
    def __str__(self):
        return 'Comment {} by {}'. format(self.body, self.author)
    

climbupproject/climbupApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    image = forms.ImageField(required=False)

    class Meta:
        #this is a comment for testing
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'image']

climbupproject/climbupApp/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect, Http404, HttpResponse, get_object_or_404
from django.http import HttpResponse
from .models import Post, City, Comment
from django.http import HttpResponse, JsonResponse
import json
from django.utils.timezone import get_current_timezone
from datetime import datetime
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def index(request):# renders the homepage with all posts
    return render(request, 'climbupApp/index.html')


def load_posts(request):# provides the data to be rendered on the home page
    posts = Post.objects.all().order_by('-created_date')# getting posts out of database
    # comments= Post.comments.all()
    post_data = []
    for post in posts: # iterating over post data, converting into dictionaries and returning JSON response
        post_data.append({
            'title': post.title,
            'text': post.text,
            'id': post.id,
            'city_id': post.city.id,
            # 'comments': post.comments,
            'scheduled_date': post.scheduled_date.strftime("%Y-%m-%d @ %H:%M"),
            'liked_by': request.user in post.likes.all(),
            'attendants': [attendee.username for attendee in post.attendees.all()],
            'likes': post.likes.count(),
            'post_image': post.post_image.url,
            'city': post.city.name,
            'author': post.author.username,
            'created_date': post.created_date.strftime('%b %d %Y'),
        })
    return JsonResponse({'posts': post_data,})


def profile_page(request): #page to render 
    return render(request, 'climbupApp/profile_page.html' )


def load_comments(request):
    comments = Comment.objects.all().order_by('-created_on') # getting comments out of the database and ordering by most recent
    comment_data = []
    for comment in comments: # iterating over comment data, converting into dictionaries and returning JSON response 
        comment_data.append({
            'post':comment.post.id,
            'author': comment.author.username,
            'body': comment.body,
            'created_on': comment.created_on.strftime('%b %d %Y'),
        })
    return JsonResponse({'comments': comment_data})


def profile_load(request):
    profile_posts = Post.objects.filter(author=request.user).order_by('-created_date')# getting the data out of the dictionary that matches the requesting user
    profile_data = []
    for post in profile_posts:# iterating over post data, converting into dictionaries and returning JSON response
        profile_data.append({
            'title': post.title,
            'text': post.text,
            'post_image': post.post_image.url,
            'id': post.id,
            'city': post.city.name,
            'author': post.author.username,
            'created_date': post.created_date.strftime('%b %d %Y'),
        })
    return JsonResponse({'profile_posts': profile_data})


def login_page(request):
    if request.method == 'POST': 
        username = request.POST['username']#assigning UN&P to variables 
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None: #checking the user exists in database.
            login(request, user) # checking credentials against database and logging user in
            messages.success(request, 'login successful')
            return redirect('climbupApp:index')
        else: #displaying error message to the user
            messages.info(request, 'invalid username or password')
    return render(request, 'climbupApp/login_page.html')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid(): #checking form data,saving to database and informing the user of success
            user = form.save()
            profile_image = form.cleaned_data['image']
            user = authenticate(username=form.cleaned_data['username'], password = form.cleaned_data['password1'])
            messages.success(request, f'Account created for{user.username}')
            login(request, user) # logging user in and redirecting to main page
            return redirect('climbupApp:index')
        else:
            messages.error(request, f'Please try again')
            return render(request, 'climbupApp/register.html', {'form': form})
    else:
        form = UserRegisterForm()
    return render(request, 'climbupApp/register.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('climbupApp:index')


def post_new(request):
    city_id = request.POST['city_id'] # assigning data to variables for saving to database from request
    created_date = request.POST['created_date']
    tz = get_current_timezone()
    scheduled_date = request.POST['scheduled_date']
    scheduled_date = tz.localize(datetime.strptime(scheduled_date, "%Y-%m-%dT%H:%M"))
    post = Post(
        title = request.POST['title'],
        text = request.POST['text'],
        post_image = request.FILES['post_image'],
        city = City.objects.get(id=city_id),
        author = request.user,
        scheduled_date = scheduled_date,
    )
    post.save()
    return HttpResponse('saved')


def save_comment(request):
    post_id = request.GET['post_id']
    tz = get_current_timezone()
    comment = Comment(
    post = Post.objects.get(id=post_id),
    body = request.POST['body'],
    author = request.user,
    )
    comment.save()
    return HttpResponse('commented')


def get_cities(request):
    cities = City.objects.all() #getting city data out of database for selects on main page 
    city_data = []
    for city in cities:
        city_data.append({
            'name':city.name,
            'id': city.id,
        })
    return JsonResponse({'cities': city_data})


def add_city(request): # assigning data to variables for saving to database
    city_name = request.POST['city_add']
    city = City(
        name = city_name
    )
    city.save()
    return HttpResponse('city added')


@login_required()
def like_post(request):
    post_id = request.GET['post_id'] #assigning "liked" post to variable
    post = Post.objects.get(id=post_id)
    user = request.user
    liked_by = True
    if post.likes.filter(id=user.id).exists():
        post.likes.remove(user)
        liked_by = False
    else:
        post.likes.add(user)
        liked_by = True
    likes = post.likes.count()
    response = { 'likes': likes, 'liked_by': liked_by}
    return JsonResponse(response)


@login_required()
def attendants(request):
    post_id = request.GET['post_id'] #getting the post object of attended post
    post = Post.objects.get(id=post_id) #getting the post id out
    user = request.user # recording the user id
    if post.attendees.filter(id=user.id).exists(): # checking if the requesting user id exists in the database, if it does we remove the user from attending
        post.attendees.remove(user)
        attended_by = ''
    else:
        post.attendees.add(user) # or if it doesn't exisist we add the user to attending
        attended_by = user.username
    attendees = post.attendees.all() 
    attendee_data = [] # creating a variable of attendees and creating a blank list
    for user in attendees: # iterating through array of attendees, and assigning to the list
        attendee_data.append(user.username)
    response = {'attendees': attendee_data, 'attended_by': attended_by} #assigning data to a dictionary and returning it in the json response.
    return JsonResponse(response)
    

@login_required
def post_edit(request):
    post_id = int(request.POST.get('post_id')) # getting the post id out
    post = Post.objects.get(id=post_id) # using the post id to find the post in the database
    post.city_id = int(request.POST['city_id']) #assigning the id to the to a variable
    post.title = request.POST['title'] # assigning the title to the databse
    post.text = request.POST['text'] # assigning the text data to the to a variable
    post.author = request.user #reassigning the author the to a variable
    post.scheduled_date = request.POST['scheduled_date'] # assigning the scheduled date to the to a variable
    post.save() # resaving the post to the database
    return HttpResponse('edited') # returning a confirmation response
    

@login_required
def delete_post(request):
    delete_post_id = int(request.POST.get('post_id')) # getting the post id out of the response
    post = Post.objects.get(id=delete_post_id) # using the post id to get the post object out of the database
    post.delete() # using the delete function to remove the post
    return HttpResponse('deleted') # returning a confirmation response

climbupproject/climbupApp/templates/climbupApp/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'climbupApp/css/styling.css'%}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <title>ClimbUp</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&family=Kaushan+Script&display=swap" rel="stylesheet">
</head>

<body id="background_image">
    <nav class="navbar navbar-light bg-light sticky-top mt-0">
        <div id="top_bar" class="container-fluid justify-content-space-around">
            <!-- <button class="btn btn-outline-success me-2" type="button">Main button</button> -->
            <a href="{% url 'climbupApp:index'%}" style="text-decoration: none;" type="button"><h1>ClimbUp</h1></a>
            {% if user.is_authenticated %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'climbupApp:profile_page' %}"
                type="button">Profile</a>
            <a class="btn btn-sm btn-outline-danger" href="{% url 'climbupApp:logout_user' %}" type="button">Log out</a>
            {% else %}
            <a class="btn btn-sm btn-outline-success" href="{% url 'climbupApp:register' %}" type="button">Register</a>
            <a class="btn btn-sm btn-outline-primary" href="{% url 'climbupApp:login_page' %}" type="button">log in</a>
            {% endif %}
            <h4>Welcome - {{user.username}}</h4>
        </div>
        {% if messages %}
        <ul class='messages'>
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}
    </nav>
    </div>
    </div>
    </div>
    {% block content%}
    {% endblock %}
</body>

</html>

climbupproject/climbupApp/templates/climbupApp/index.html
{% extends 'climbupApp/base.html'%}
{% block content %}
<div id="app" class="container ">
    <!-- add city modal  -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true"> modal starts here
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel"><i class="bi bi-building">Enter a city</i></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="">
                        <textarea class="form-control" v-model="city_add" id="city_add" rows="3"></textarea>
                        <button type="button" v-on:click="addCity" data-bs-dismiss="modal" class="btn btn-primary">Add
                            city</button>
                    </form>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
    <!-- new post form -->
    <div class="col" id="new_post">
        <div class="form-group">
            <label for="new_post_form"></label>
            <input type="title" class="form-control" v-model="title" id="new_post_form" placeholder="What's happening?">
        </div>
        <textarea class="form-control" v-model="text" id="FormControlTextarea1" rows="3"></textarea>
        <select class="form-select form-select-sm" v-model="city_id" aria-label=".form-select-sm ">
            <option value="" disabled selected>Select a City</option>
            <option v-for="city in cities" placeholder="What's happening?" v-bind:value="city.id">[[city.name]]</option>
        </select>
        <input class="form-control form-control-sm" id="post_image" type="file" accept="image/*" />
        <input type="datetime-local" class="form-control" id="scheduled_date" v-model="scheduled_date">
        <div class="d-flex justify-content-evenly" id="new_postbtns">
            <button type="button" v-on:click="postNew" class="btn btn-primary">Send it</button>
            <!-- button triggers add city modal to open -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Add a City
            </button>
        </div>
        <div class=" container row mt-1">
            <!-- select dropdown for selecting a city to assign to the post -->
            <select class="form-select form-select-sm" v-model="city_sort" aria-label=".form-select-sm ">
                <option value="" disabled selected>Select a City</option>
                <option v-for="city in cities" v-bind:value="city.id">[[city.name]]</option>
            </select>
            <button type="button" v-on:click="postIndex" class="btn btn-light ">sort by city</button>
        </div>
    </div>
    <!-- main post bodies start here -->
    <div class="container m-o mt-1" id="card" data-aos="fade-up" data-aos-duration="3000" v-for="post in vue_posts"
        style="width: 100%;">
        <img v-bind:src="post.post_image" class="card-img-top mt-1" alt="...">
        <div class="card-body">
            <div>Author- [[ post.author]]</div>
            <div>Location- [[post.city]]</div>
            <div>posted- [[post.created_date]]</div>
            <div>scheduled- [[post.scheduled_date]]</div>
            <hr>
            <h5 class="card-title">[[post.title]]</h5>
            <p class="card-text">
                [[post.text]]
            </p>
            <hr>
            <!-- checking if the user is authenticated before allowing liking and attending -->
            {% if user.is_authenticated %}
            <div class="d-flex justify-content-evenly">
                <!-- button prompts modal to open for commenting -->
                <button type="button" class="btn btn-primary" v-on:click="commented_post_id = post.id" data-bs-toggle="modal"
                    data-bs-target="#Modalcomment">
                    Add a comment
                </button>
                <button type='button' class="btn btn-floating mb-1" data-mdb-ripple-color="dark"
                    v-on:click="likePost(post)">[[post.liked? '👎': '👍' ]]</button>
                <button type='button' class='btn btn-floatin mb-1' data-mdb-ripple-color='dark'
                    v-on:click="Attending(post)">🧗</button>
            </div>
            {% endif %}
            <!-- displaying the posts comments and likes -->
            <div class="card-text d-flex justify-content-evenly">
                <div>comments</div>
                <div>Likes-[[post.likes]]</div>
                <div>attendants-[[post.attendants.join(', ')]]</div>
            </div>
            <hr>
            <!-- single accordian for the posts comments -->
            <div class="accordion accordion-flush" id="accordionFlush">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                            Comments
                        </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                        data-bs-parent="#accordionFlush">
                        <div class="accordion-body" v-for="(comment, index) in comments" v-if="comment.post == post.id">
                            <h1>[[comment.author]]</h1>
                            <p>[[ comment.body ]]</p>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- modal for commenting -->
    <div class="modal fade" id="Modalcomment" tabindex="-1" aria-labelledby="ModalLabel"
    aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLabel">Comment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <textarea class="form-control" v-model="body" id="add_comment" cols="30"
                    rows="10"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" v-on:click="vueSaveComment" data-bs-dismiss="modal" class="btn btn-primary">Save comment</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script>
    let app = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            vue_posts: [],
            text: '',
            title: '',
            body: '',
            comments: [],
            commented_post_id: 0,
            modal: null,
            attendees: '',
            likes: '',
            created_date: '',
            scheduled_date: '',
            cities: '',
            city_id: '',
            city_add: '',
            city_sort: '',
        },
        methods: {
            // loads posts into vue for rendering
            postIndex: function () {
                axios({
                    url: "{% url 'climbupApp:load_posts' %}",
                    method: 'get',
                    params: {
                        sort: this.city_sort,
                    }
                }).then(response => {
                    if (this.city_sort) {
                        this.vue_posts = response.data.posts.filter(post => this.city_sort === post.city_id)
                    }
                    else {
                        this.vue_posts = response.data.posts
                    }
                })
            },
            // load comments into vue for rendering
            vueComments: function () {
                axios({
                    url: "{% url 'climbupApp:load_comments' %}",
                    method: 'get',
                }).then(response => {
                    this.comments = response.data.comments
                })
            },
            addCity: function () {
                let form_data = new FormData()
                form_data.append('city_add', this.city_add)
                axios({
                    url: "{% url 'climbupApp:add_city'%}",
                    method: 'post',
                    data: form_data,
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}"
                    }
                }).then(response => {
                    this.getCities()
                })
            },
            likePost: function (post) {
                axios({
                    url: "{% url 'climbupApp:like_post'%}",
                    method: 'get',
                    params: {
                        post_id: post.id
                    }
                }).then(response => {
                    this.likes = response.data.likes
                    this.postIndex()
                    this.vueComments()
                })
            },
            Attending: function (post) {
                axios({
                    url: "{% url 'climbupApp:attendants'%}",
                    method: 'get',
                    params: {
                        post_id: post.id
                    }
                }).then(response => {
                    post.attendees = response.data.attendees
                    console.log(this.attendees, 'this.attendees')
                    this.postIndex()
                })
            },
            getCities: function () {
                axios({
                    url: "{% url 'climbupApp:get_cities' %}",
                    method: 'get',
                }).then(response => {
                    this.cities = response.data.cities
                })
            },
            vueSaveComment: function () {
                console.log(this.commented_post_id)
                let form_data = new FormData()
                form_data.append('body', this.body)
                axios({
                    url: "{% url 'climbupApp:save_comment'%}",
                    method: "post",
                    params:{
                        post_id: this.commented_post_id
                    },
                    data: form_data,
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}"
                    }
                }).then(response => {
                    console.log(response)
                    this.vueComments()
                    this.body = ''
                })
            },
            postNew: function () {
                let form_data = new FormData()
                let post_image = document.querySelector('#post_image')
                form_data.append('post_image', post_image.files[0])
                form_data.append('text', this.text)
                form_data.append('title', this.title)
                form_data.append('city_id', this.city_id)
                form_data.append('attendees', this.attendees)
                form_data.append('likes', this.likes)
                form_data.append('created_date', this.created_date)
                form_data.append('scheduled_date', this.scheduled_date)
                axios({
                    url: "{% url 'climbupApp:post_new' %}",
                    method: "post",
                    data: form_data,
                    headers: {
                        "X-CSRFToken": "{{ csrf_token }}"
                    }
                }).then(response => {
                    this.text = ''
                    this.title = ''
                    this.scheduled_date = ''
                    post_image.value = ''
                    this.city_id = ''
                    this.postIndex()
                })
            },
            openModal: function () {
                this.modal.show()
                console.log('it works')
            }
        },
        created: function () {
            AOS.init()
            this.modal = new bootstrap.Modal(document.querySelector('.modal'), {})
            this.postIndex()
            this.getCities()
            this.vueComments()
        },
    })
</script>
{% endblock %}

climbupproject/climbupApp/templates/climbupApp/login_page.html
{% extends 'climbupApp/base.html'%}  
<!-- loading stying and navbar from base & using crispy forms for standardized login info -->
{% load crispy_forms_tags %}
{% block content %}

<div class="text-center mb-1" id="registration"> Log in below </div>
<div id="registration">
  <form action="" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="username" class="form-label">username</label>
      <input type="username" name="username" class="form-control" id="username1">
    </div>
    <!-- displays an error or success message depending on user input -->
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" id="Password1">
    </div>
    <button type="submit" class="btn btn-primary">Sign In</button>
  </form>
</div>
{% endblock %}

climbupproject/climbupApp/templates/climbupApp/my_city.html
{% extends 'climbupApp/base.html'%}

{% block content %}








{% endblock %}

climbupproject/climbupApp/templates/climbupApp/register.html
{% extends 'climbupApp/base.html'%}
<!-- loading stying and navbar from base & using crispy forms for standardized login info -->
{% load crispy_forms_tags %}
{% block content %}
<div class="container content-section" id="registration">
    <form action='{% url "climbupApp:register"%}' method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">join today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">sign up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a href="{% url 'climbupApp:login_page' %}" class="ml-2"> Sign in</a>
        </small>
    </div>
</div>
{%endblock content%}